{"_default": {"1": {"issues": [{"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/9", "repository_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect", "labels_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/9/labels{/name}", "comments_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/9/comments", "events_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/9/events", "html_url": "https://github.com/waltervargas/prestashoperpconnect/issues/9", "id": 42599970, "number": 9, "title": "error on sync order lines.", "user": {"login": "waltervargas", "id": 74988, "avatar_url": "https://avatars2.githubusercontent.com/u/74988?v=4", "gravatar_id": "", "url": "https://api.github.com/users/waltervargas", "html_url": "https://github.com/waltervargas", "followers_url": "https://api.github.com/users/waltervargas/followers", "following_url": "https://api.github.com/users/waltervargas/following{/other_user}", "gists_url": "https://api.github.com/users/waltervargas/gists{/gist_id}", "starred_url": "https://api.github.com/users/waltervargas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/waltervargas/subscriptions", "organizations_url": "https://api.github.com/users/waltervargas/orgs", "repos_url": "https://api.github.com/users/waltervargas/repos", "events_url": "https://api.github.com/users/waltervargas/events{/privacy}", "received_events_url": "https://api.github.com/users/waltervargas/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2014-09-12T06:21:07Z", "updated_at": "2014-09-12T06:29:15Z", "closed_at": null, "author_association": "OWNER", "body": "``` python\n2014-09-12 05:55:57,223 8183 ERROR salling5 openerp.addons.connector.queue.worker: Traceback (most recent call last):\n  File \"/opt/openerp/addons-connector/connector/queue/worker.py\", line 122, in run_job\n    job.perform(session)\n  File \"/opt/openerp/addons-connector/connector/queue/job.py\", line 490, in perform\n    self.result = self.func(session, *self.args, **self.kwargs)\n  File \"/opt/openerp/addons-connector/prestashoperpconnect/unit/import_synchronizer.py\", line 1036, in import_record\n    importer.run(prestashop_id)\n  File \"/opt/openerp/addons-connector/prestashoperpconnect/unit/import_synchronizer.py\", line 149, in run\n    erp_id = self._create(record)\n  File \"/opt/openerp/addons-connector/prestashoperpconnect/unit/import_synchronizer.py\", line 92, in _create\n    vals = data.values()\n  File \"/opt/openerp/addons-connector/connector/unit/mapper.py\", line 902, in values\n    values = self._mapper._apply(self, options=options)\n  File \"/opt/openerp/addons-connector/connector/unit/mapper.py\", line 641, in _apply\n    return self._apply_with_options(map_record)\n  File \"/opt/openerp/addons-connector/connector/unit/mapper.py\", line 691, in _apply_with_options\n    to_attr, model_name)\n  File \"/opt/openerp/addons-connector/prestashoperpconnect/unit/mapper.py\", line 403, in _map_child\n    child_records = from_attr(self, record)\n  File \"/opt/openerp/addons-connector/prestashoperpconnect/unit/mapper.py\", line 387, in _get_sale_order_lines\n    orders = record['associations'].get('order_rows', {}).get('order_row', [])\nTypeError: 'MapRecord' object has no attribute '__getitem__'\n```\n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/9/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}, {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/8", "repository_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect", "labels_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/8/comments", "events_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/8/events", "html_url": "https://github.com/waltervargas/prestashoperpconnect/issues/8", "id": 40431364, "number": 8, "title": "duplicate key value error on import products", "user": {"login": "waltervargas", "id": 74988, "avatar_url": "https://avatars2.githubusercontent.com/u/74988?v=4", "gravatar_id": "", "url": "https://api.github.com/users/waltervargas", "html_url": "https://github.com/waltervargas", "followers_url": "https://api.github.com/users/waltervargas/followers", "following_url": "https://api.github.com/users/waltervargas/following{/other_user}", "gists_url": "https://api.github.com/users/waltervargas/gists{/gist_id}", "starred_url": "https://api.github.com/users/waltervargas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/waltervargas/subscriptions", "organizations_url": "https://api.github.com/users/waltervargas/orgs", "repos_url": "https://api.github.com/users/waltervargas/repos", "events_url": "https://api.github.com/users/waltervargas/events{/privacy}", "received_events_url": "https://api.github.com/users/waltervargas/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2014-08-17T10:32:03Z", "updated_at": "2014-11-29T11:45:47Z", "closed_at": null, "author_association": "OWNER", "body": "``` python\n  File \"/home/vagrant/addons/connector/queue/worker.py\", line 122, in run_job\n    job.perform(session)\n  File \"/home/vagrant/addons/connector/queue/job.py\", line 490, in perform\n    self.result = self.func(session, *self.args, **self.kwargs)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 1030, in import_record\n    importer.run(prestashop_id)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 680, in run\n    self._after_import(erp_id)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 768, in _after_import\n    self.import_combinations()\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 799, in import_combinations\n    combination['id']\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 1030, in import_record\n    importer.run(prestashop_id)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 143, in run\n    self._import_dependencies()\n  File \"/home/vagrant/addons/prestashoperpconnect/product_combination.py\", line 65, in _import_dependencies\n    'prestashop.product.combination.option',\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 173, in _check_dependency\n    ext_id\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 1030, in import_record\n    importer.run(prestashop_id)\n  File \"/home/vagrant/addons/prestashoperpconnect/product_combination.py\", line 342, in run\n    super(ProductCombinationOptionRecordImport, self).run(ext_id)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 160, in run\n    erp_id = self._create(record)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 102, in _create\n    context=context\n  File \"/home/vagrant/addons/connector/producer.py\", line 43, in create\n    record_id = create_original(self, cr, uid, vals, context=context)\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/orm.py\", line 4444, in create\n    record_id = self.pool.get(table).create(cr, user, tocreate[table], context=parent_context)\n  File \"/home/vagrant/addons/base_custom_attributes/custom_attributes.py\", line 312, in create\n    return super(attribute_attribute, self).create(cr, uid, vals, context)\n  File \"/home/vagrant/addons/connector/producer.py\", line 43, in create\n    record_id = create_original(self, cr, uid, vals, context=context)\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/orm.py\", line 4444, in create\n    record_id = self.pool.get(table).create(cr, user, tocreate[table], context=parent_context)\n  File \"/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_model.py\", line 345, in create\n    res = super(ir_model_fields,self).create(cr, user, vals, context)\n  File \"/home/vagrant/addons/connector/producer.py\", line 43, in create\n    record_id = create_original(self, cr, uid, vals, context=context)\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/orm.py\", line 4515, in create\n    cr.execute('insert into \"'+self._table+'\" (id'+upd0+\") values (\"+str(id_new)+upd1+')', tuple(upd2))\n  File \"/usr/lib/pymodules/python2.7/openerp/sql_db.py\", line 161, in wrapper\n    return f(self, *args, **kwargs)\n  File \"/usr/lib/pymodules/python2.7/openerp/sql_db.py\", line 226, in execute\n    res = self._obj.execute(query, params)\nIntegrityError: duplicate key value violates unique constraint \"ir_model_fields_name_model_uniq\"\nDETAIL:  Key (name, model_id)=(x_Color, 149) already exists.\n```\n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/8/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}, {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/7", "repository_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect", "labels_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/7/labels{/name}", "comments_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/7/comments", "events_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/7/events", "html_url": "https://github.com/waltervargas/prestashoperpconnect/issues/7", "id": 40222173, "number": 7, "title": "Error on Import customer groups and customers ", "user": {"login": "waltervargas", "id": 74988, "avatar_url": "https://avatars2.githubusercontent.com/u/74988?v=4", "gravatar_id": "", "url": "https://api.github.com/users/waltervargas", "html_url": "https://github.com/waltervargas", "followers_url": "https://api.github.com/users/waltervargas/followers", "following_url": "https://api.github.com/users/waltervargas/following{/other_user}", "gists_url": "https://api.github.com/users/waltervargas/gists{/gist_id}", "starred_url": "https://api.github.com/users/waltervargas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/waltervargas/subscriptions", "organizations_url": "https://api.github.com/users/waltervargas/orgs", "repos_url": "https://api.github.com/users/waltervargas/repos", "events_url": "https://api.github.com/users/waltervargas/events{/privacy}", "received_events_url": "https://api.github.com/users/waltervargas/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2014-08-14T04:29:50Z", "updated_at": "2014-08-14T04:30:04Z", "closed_at": null, "author_association": "OWNER", "body": "``` python\n/usr/local/lib/python2.7/dist-packages/prestapyt-0.6.1-py2.7.egg/prestapyt/prestapyt.py:144: UserWarning: This library may not be compatible with this version of PrestaShop (1.6.0.8). Please upgrade/downgrade this library\n  \"Please upgrade/downgrade this library\") % (version,))\n2014-08-13 18:15:23,645 10554 ERROR salling5 openerp.addons.connector.queue.worker: Traceback (most recent call last):\n  File \"/home/vagrant/addons/connector/queue/worker.py\", line 122, in run_job\n    job.perform(session)\n  File \"/home/vagrant/addons/connector/queue/job.py\", line 490, in perform\n    self.result = self.func(session, *self.args, **self.kwargs)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 1030, in import_record\n    importer.run(prestashop_id)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 143, in run\n    self._import_dependencies()\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 321, in _import_dependencies\n    self.create_account(self.prestashop_record['id'], name)\nAttributeError: 'ResPartnerRecordImport' object has no attribute 'create_account'\n```\n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/7/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}], "commits": [{"sha": "affd14716732358086ef4ec4374246343294e110", "commit": {"author": {"name": "Walter Vargas", "email": "walter@covetel.com.ve", "date": "2014-07-10T18:33:39Z"}, "committer": {"name": "Walter Vargas", "email": "walter@covetel.com.ve", "date": "2014-07-10T18:33:39Z"}, "message": "Update INSTALL.org", "tree": {"sha": "c73f83878fd869c2be48f760f848484ed3dd6953", "url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/git/trees/c73f83878fd869c2be48f760f848484ed3dd6953"}, "url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/git/commits/affd14716732358086ef4ec4374246343294e110", "comment_count": 1, "verification": {"verified": false, "reason": "unsigned", "signature": null, "payload": null}}, "url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/commits/affd14716732358086ef4ec4374246343294e110", "html_url": "https://github.com/waltervargas/prestashoperpconnect/commit/affd14716732358086ef4ec4374246343294e110", "comments_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/commits/affd14716732358086ef4ec4374246343294e110/comments", "author": null, "committer": null, "parents": [{"sha": "3e75257a1931925d10b68a49e16dc488c96ae3be", "url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/commits/3e75257a1931925d10b68a49e16dc488c96ae3be", "html_url": "https://github.com/waltervargas/prestashoperpconnect/commit/3e75257a1931925d10b68a49e16dc488c96ae3be"}]}, {"sha": "3e75257a1931925d10b68a49e16dc488c96ae3be", "commit": {"author": {"name": "Walter Vargas", "email": "walter@covetel.com.ve", "date": "2014-07-10T18:32:36Z"}, "committer": {"name": "Walter Vargas", "email": "walter@covetel.com.ve", "date": "2014-07-10T18:32:36Z"}, "message": "Create INSTALL.org", "tree": {"sha": "6662536c52669c822e0f3644e229cb569eaf760a", "url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/git/trees/6662536c52669c822e0f3644e229cb569eaf760a"}, "url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/git/commits/3e75257a1931925d10b68a49e16dc488c96ae3be", "comment_count": 0, "verification": {"verified": false, "reason": "unsigned", "signature": null, "payload": null}}, "url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/commits/3e75257a1931925d10b68a49e16dc488c96ae3be", "html_url": "https://github.com/waltervargas/prestashoperpconnect/commit/3e75257a1931925d10b68a49e16dc488c96ae3be", "comments_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/commits/3e75257a1931925d10b68a49e16dc488c96ae3be/comments", "author": null, "committer": null, "parents": [{"sha": "f2f388af055d5e742eb4e82e4711a2c74cf2ef9e", "url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/commits/f2f388af055d5e742eb4e82e4711a2c74cf2ef9e", "html_url": "https://github.com/waltervargas/prestashoperpconnect/commit/f2f388af055d5e742eb4e82e4711a2c74cf2ef9e"}]}, {"sha": "f2f388af055d5e742eb4e82e4711a2c74cf2ef9e", "commit": {"author": {"name": "Walter Vargas", "email": "walter@covetel.com.ve", "date": "2014-07-08T09:28:29Z"}, "committer": {"name": "Walter Vargas", "email": "walter@covetel.com.ve", "date": "2014-07-08T09:28:29Z"}, "message": "the first commit", "tree": {"sha": "ca30107764ec4d4e75c1816b46b372ad14c247cb", "url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/git/trees/ca30107764ec4d4e75c1816b46b372ad14c247cb"}, "url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/git/commits/f2f388af055d5e742eb4e82e4711a2c74cf2ef9e", "comment_count": 0, "verification": {"verified": false, "reason": "unsigned", "signature": null, "payload": null}}, "url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/commits/f2f388af055d5e742eb4e82e4711a2c74cf2ef9e", "html_url": "https://github.com/waltervargas/prestashoperpconnect/commit/f2f388af055d5e742eb4e82e4711a2c74cf2ef9e", "comments_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/commits/f2f388af055d5e742eb4e82e4711a2c74cf2ef9e/comments", "author": null, "committer": null, "parents": []}], "pull_requests": [], "issue_comments": [{"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/49486248", "html_url": "https://github.com/waltervargas/prestashoperpconnect/issues/3#issuecomment-49486248", "issue_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/3", "id": 49486248, "user": {"login": "waltervargas", "id": 74988, "avatar_url": "https://avatars2.githubusercontent.com/u/74988?v=4", "gravatar_id": "", "url": "https://api.github.com/users/waltervargas", "html_url": "https://github.com/waltervargas", "followers_url": "https://api.github.com/users/waltervargas/followers", "following_url": "https://api.github.com/users/waltervargas/following{/other_user}", "gists_url": "https://api.github.com/users/waltervargas/gists{/gist_id}", "starred_url": "https://api.github.com/users/waltervargas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/waltervargas/subscriptions", "organizations_url": "https://api.github.com/users/waltervargas/orgs", "repos_url": "https://api.github.com/users/waltervargas/repos", "events_url": "https://api.github.com/users/waltervargas/events{/privacy}", "received_events_url": "https://api.github.com/users/waltervargas/received_events", "type": "User", "site_admin": false}, "created_at": "2014-07-18T22:23:02Z", "updated_at": "2014-07-18T22:23:02Z", "author_association": "OWNER", "body": "fixed in the commit f57b7cfae698c5e846987c27217653032d8322ea\n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/49486248/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}, {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/49490952", "html_url": "https://github.com/waltervargas/prestashoperpconnect/issues/6#issuecomment-49490952", "issue_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/6", "id": 49490952, "user": {"login": "waltervargas", "id": 74988, "avatar_url": "https://avatars2.githubusercontent.com/u/74988?v=4", "gravatar_id": "", "url": "https://api.github.com/users/waltervargas", "html_url": "https://github.com/waltervargas", "followers_url": "https://api.github.com/users/waltervargas/followers", "following_url": "https://api.github.com/users/waltervargas/following{/other_user}", "gists_url": "https://api.github.com/users/waltervargas/gists{/gist_id}", "starred_url": "https://api.github.com/users/waltervargas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/waltervargas/subscriptions", "organizations_url": "https://api.github.com/users/waltervargas/orgs", "repos_url": "https://api.github.com/users/waltervargas/repos", "events_url": "https://api.github.com/users/waltervargas/events{/privacy}", "received_events_url": "https://api.github.com/users/waltervargas/received_events", "type": "User", "site_admin": false}, "created_at": "2014-07-18T23:27:50Z", "updated_at": "2014-07-18T23:27:50Z", "author_association": "OWNER", "body": "## Problem for 'Synchronize Metadata'\n\nconnector: 2.2.0 (branch 7.0 from github)\nconnector_ecommerce: 2.1.0\nprestashoperpconnect: 0.3\n\n```\n2014-07-18 21:43:10,169 5947 ERROR salling3 openerp.osv.osv: Uncaught exception\nTraceback (most recent call last):\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/osv.py\", line 132, in wrapper\n    return f(self, dbname, *args, **kwargs)\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/osv.py\", line 199, in execute\n    res = self.execute_cr(cr, uid, obj, method, *args, **kw)\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/osv.py\", line 187, in execute_cr\n    return getattr(object, method)(cr, uid, *args, **kw)\n  File \"/home/vagrant/addons/prestashoperpconnect/models/prestashop_model.py\", line 116, in synchronize_metadata\n    import_batch(session, model, backend_id)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 1014, in import_batch\n    importer.run(filters=filters, **kwargs)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 183, in run\n    record_ids = self._run_page(filters, **kwargs)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 193, in _run_page\n    self._import_record(record_id, **kwargs)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 259, in _import_record\n    record\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 1022, in import_record\n    importer.run(prestashop_id)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 149, in run\n    erp_id = self._create(record)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 98, in _create\n    context=context\n  File \"/home/vagrant/addons/connector/producer.py\", line 45, in create\n    record_id = create_original(self, cr, uid, vals, context=context)\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/orm.py\", line 4394, in create\n    if vals.pop(f, None) is not None:\nAttributeError: 'MapRecord' object has no attribute 'pop'\n2014-07-18 21:43:10,179 5947 ERROR salling3 openerp.netsvc: 'MapRecord' object has no attribute 'pop'\nTraceback (most recent call last):\n  File \"/usr/lib/pymodules/python2.7/openerp/netsvc.py\", line 296, in dispatch_rpc\n    result = ExportService.getService(service_name).dispatch(method, params)\n  File \"/usr/lib/pymodules/python2.7/openerp/service/web_services.py\", line 626, in dispatch\n    res = fn(db, uid, *params)\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/osv.py\", line 190, in execute_kw\n    return self.execute(db, uid, obj, method, *args, **kw or {})\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/osv.py\", line 132, in wrapper\n    return f(self, dbname, *args, **kwargs)\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/osv.py\", line 199, in execute\n    res = self.execute_cr(cr, uid, obj, method, *args, **kw)\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/osv.py\", line 187, in execute_cr\n    return getattr(object, method)(cr, uid, *args, **kw)\n  File \"/home/vagrant/addons/prestashoperpconnect/models/prestashop_model.py\", line 116, in synchronize_metadata\n    import_batch(session, model, backend_id)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 1014, in import_batch\n    importer.run(filters=filters, **kwargs)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 183, in run\n    record_ids = self._run_page(filters, **kwargs)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 193, in _run_page\n    self._import_record(record_id, **kwargs)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 259, in _import_record\n    record\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 1022, in import_record\n    importer.run(prestashop_id)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 149, in run\n    erp_id = self._create(record)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 98, in _create\n    context=context\n  File \"/home/vagrant/addons/connector/producer.py\", line 45, in create\n    record_id = create_original(self, cr, uid, vals, context=context)\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/orm.py\", line 4394, in create\n    if vals.pop(f, None) is not None:\nAttributeError: 'MapRecord' object has no attribute 'pop'\n```\n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/49490952/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}, {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/49922570", "html_url": "https://github.com/waltervargas/prestashoperpconnect/issues/6#issuecomment-49922570", "issue_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/6", "id": 49922570, "user": {"login": "guerrerocarlos", "id": 82532, "avatar_url": "https://avatars2.githubusercontent.com/u/82532?v=4", "gravatar_id": "", "url": "https://api.github.com/users/guerrerocarlos", "html_url": "https://github.com/guerrerocarlos", "followers_url": "https://api.github.com/users/guerrerocarlos/followers", "following_url": "https://api.github.com/users/guerrerocarlos/following{/other_user}", "gists_url": "https://api.github.com/users/guerrerocarlos/gists{/gist_id}", "starred_url": "https://api.github.com/users/guerrerocarlos/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/guerrerocarlos/subscriptions", "organizations_url": "https://api.github.com/users/guerrerocarlos/orgs", "repos_url": "https://api.github.com/users/guerrerocarlos/repos", "events_url": "https://api.github.com/users/guerrerocarlos/events{/privacy}", "received_events_url": "https://api.github.com/users/guerrerocarlos/received_events", "type": "User", "site_admin": false}, "created_at": "2014-07-23T19:26:41Z", "updated_at": "2014-07-23T19:26:41Z", "author_association": "NONE", "body": "En https://github.com/waltervargas/prestashoperpconnect/blob/master/prestashoperpconnect/unit/import_synchronizer.py#L102\n\nreemplacen:\n  return erp_id \n\npor:\n return [erp_id]\n\nAparentemente se espera que devuelva es una lista a la que se le pueda hacer \".pop()\"\nhttps://docs.python.org/2/tutorial/datastructures.html#more-on-lists\n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/49922570/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}, {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/50133646", "html_url": "https://github.com/waltervargas/prestashoperpconnect/issues/6#issuecomment-50133646", "issue_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/6", "id": 50133646, "user": {"login": "waltervargas", "id": 74988, "avatar_url": "https://avatars2.githubusercontent.com/u/74988?v=4", "gravatar_id": "", "url": "https://api.github.com/users/waltervargas", "html_url": "https://github.com/waltervargas", "followers_url": "https://api.github.com/users/waltervargas/followers", "following_url": "https://api.github.com/users/waltervargas/following{/other_user}", "gists_url": "https://api.github.com/users/waltervargas/gists{/gist_id}", "starred_url": "https://api.github.com/users/waltervargas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/waltervargas/subscriptions", "organizations_url": "https://api.github.com/users/waltervargas/orgs", "repos_url": "https://api.github.com/users/waltervargas/repos", "events_url": "https://api.github.com/users/waltervargas/events{/privacy}", "received_events_url": "https://api.github.com/users/waltervargas/received_events", "type": "User", "site_admin": false}, "created_at": "2014-07-25T10:41:21Z", "updated_at": "2014-07-25T10:41:21Z", "author_association": "OWNER", "body": "Gracias my friend, hoy pruebo.\n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/50133646/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}, {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/50225766", "html_url": "https://github.com/waltervargas/prestashoperpconnect/issues/6#issuecomment-50225766", "issue_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/6", "id": 50225766, "user": {"login": "waltervargas", "id": 74988, "avatar_url": "https://avatars2.githubusercontent.com/u/74988?v=4", "gravatar_id": "", "url": "https://api.github.com/users/waltervargas", "html_url": "https://github.com/waltervargas", "followers_url": "https://api.github.com/users/waltervargas/followers", "following_url": "https://api.github.com/users/waltervargas/following{/other_user}", "gists_url": "https://api.github.com/users/waltervargas/gists{/gist_id}", "starred_url": "https://api.github.com/users/waltervargas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/waltervargas/subscriptions", "organizations_url": "https://api.github.com/users/waltervargas/orgs", "repos_url": "https://api.github.com/users/waltervargas/repos", "events_url": "https://api.github.com/users/waltervargas/events{/privacy}", "received_events_url": "https://api.github.com/users/waltervargas/received_events", "type": "User", "site_admin": false}, "created_at": "2014-07-26T07:13:39Z", "updated_at": "2014-07-26T07:13:39Z", "author_association": "OWNER", "body": "Not working my friend, the same error: \n\n```\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 149, in run\n    erp_id = self._create(record)\n  File \"/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py\", line 98, in _create\n    context=context\n  File \"/home/vagrant/addons/connector/producer.py\", line 43, in create\n    record_id = create_original(self, cr, uid, vals, context=context)\n  File \"/usr/lib/pymodules/python2.7/openerp/osv/orm.py\", line 4394, in create\n    if vals.pop(f, None) is not None:\nAttributeError: 'MapRecord' object has no attribute 'pop'\n```\n\nI thing that `vals` is equal to None \n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/50225766/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}, {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/52142681", "html_url": "https://github.com/waltervargas/prestashoperpconnect/issues/6#issuecomment-52142681", "issue_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/6", "id": 52142681, "user": {"login": "waltervargas", "id": 74988, "avatar_url": "https://avatars2.githubusercontent.com/u/74988?v=4", "gravatar_id": "", "url": "https://api.github.com/users/waltervargas", "html_url": "https://github.com/waltervargas", "followers_url": "https://api.github.com/users/waltervargas/followers", "following_url": "https://api.github.com/users/waltervargas/following{/other_user}", "gists_url": "https://api.github.com/users/waltervargas/gists{/gist_id}", "starred_url": "https://api.github.com/users/waltervargas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/waltervargas/subscriptions", "organizations_url": "https://api.github.com/users/waltervargas/orgs", "repos_url": "https://api.github.com/users/waltervargas/repos", "events_url": "https://api.github.com/users/waltervargas/events{/privacy}", "received_events_url": "https://api.github.com/users/waltervargas/received_events", "type": "User", "site_admin": false}, "created_at": "2014-08-14T04:29:03Z", "updated_at": "2014-08-14T04:29:03Z", "author_association": "OWNER", "body": "Problem fixed in the commit cd261e25b9a122bab55415ebde0bbf5ed7780917\n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/52142681/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}, {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/55366154", "html_url": "https://github.com/waltervargas/prestashoperpconnect/issues/9#issuecomment-55366154", "issue_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/9", "id": 55366154, "user": {"login": "anex", "id": 687353, "avatar_url": "https://avatars3.githubusercontent.com/u/687353?v=4", "gravatar_id": "", "url": "https://api.github.com/users/anex", "html_url": "https://github.com/anex", "followers_url": "https://api.github.com/users/anex/followers", "following_url": "https://api.github.com/users/anex/following{/other_user}", "gists_url": "https://api.github.com/users/anex/gists{/gist_id}", "starred_url": "https://api.github.com/users/anex/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/anex/subscriptions", "organizations_url": "https://api.github.com/users/anex/orgs", "repos_url": "https://api.github.com/users/anex/repos", "events_url": "https://api.github.com/users/anex/events{/privacy}", "received_events_url": "https://api.github.com/users/anex/received_events", "type": "User", "site_admin": false}, "created_at": "2014-09-12T06:29:15Z", "updated_at": "2014-09-12T06:29:15Z", "author_association": "COLLABORATOR", "body": "After try fix the above error:\n\n``` python\norders = record._source['associations'].get('order_rows', {}).get('order_row', [])\n```\n\nI get the following error:\n\n``` python\n2014-09-12 06:24:09,770 6523 ERROR salling openerp.addons.connector.queue.worker: Traceback (most recent call last):\n  File \"/opt/openerp/addons-connector/connector/queue/worker.py\", line 122, in run_job\n    job.perform(session)\n  File \"/opt/openerp/addons-connector/connector/queue/job.py\", line 490, in perform\n    self.result = self.func(session, *self.args, **self.kwargs)\n  File \"/opt/openerp/addons-connector/prestashoperpconnect/unit/import_synchronizer.py\", line 1036, in import_record\n    importer.run(prestashop_id)\n  File \"/opt/openerp/addons-connector/prestashoperpconnect/unit/import_synchronizer.py\", line 149, in run\n    erp_id = self._create(record)\n  File \"/opt/openerp/addons-connector/prestashoperpconnect/unit/import_synchronizer.py\", line 92, in _create\n    vals = data.values()\n  File \"/opt/openerp/addons-connector/connector/unit/mapper.py\", line 902, in values\n    values = self._mapper._apply(self, options=options)\n  File \"/opt/openerp/addons-connector/connector/unit/mapper.py\", line 641, in _apply\n    return self._apply_with_options(map_record)\n  File \"/opt/openerp/addons-connector/connector/unit/mapper.py\", line 691, in _apply_with_options\n    to_attr, model_name)\n  File \"/opt/openerp/addons-connector/prestashoperpconnect/unit/mapper.py\", line 414, in _map_child\n    mapper = self._init_child_mapper(model_name)\nAttributeError: 'SaleOrderMapper' object has no attribute '_init_child_mapper'\n```\n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/55366154/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}, {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/64949329", "html_url": "https://github.com/waltervargas/prestashoperpconnect/issues/8#issuecomment-64949329", "issue_url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/8", "id": 64949329, "user": {"login": "percevaq", "id": 7541214, "avatar_url": "https://avatars2.githubusercontent.com/u/7541214?v=4", "gravatar_id": "", "url": "https://api.github.com/users/percevaq", "html_url": "https://github.com/percevaq", "followers_url": "https://api.github.com/users/percevaq/followers", "following_url": "https://api.github.com/users/percevaq/following{/other_user}", "gists_url": "https://api.github.com/users/percevaq/gists{/gist_id}", "starred_url": "https://api.github.com/users/percevaq/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/percevaq/subscriptions", "organizations_url": "https://api.github.com/users/percevaq/orgs", "repos_url": "https://api.github.com/users/percevaq/repos", "events_url": "https://api.github.com/users/percevaq/events{/privacy}", "received_events_url": "https://api.github.com/users/percevaq/received_events", "type": "User", "site_admin": false}, "created_at": "2014-11-29T11:45:47Z", "updated_at": "2014-11-29T11:45:47Z", "author_association": "NONE", "body": "Hello:\nYou fix this problem?\n\nThank\n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/issues/comments/64949329/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}], "commit_comments": [{"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/comments/7414948", "html_url": "https://github.com/waltervargas/prestashoperpconnect/commit/affd14716732358086ef4ec4374246343294e110#commitcomment-7414948", "id": 7414948, "user": {"login": "mytika", "id": 8324178, "avatar_url": "https://avatars0.githubusercontent.com/u/8324178?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mytika", "html_url": "https://github.com/mytika", "followers_url": "https://api.github.com/users/mytika/followers", "following_url": "https://api.github.com/users/mytika/following{/other_user}", "gists_url": "https://api.github.com/users/mytika/gists{/gist_id}", "starred_url": "https://api.github.com/users/mytika/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mytika/subscriptions", "organizations_url": "https://api.github.com/users/mytika/orgs", "repos_url": "https://api.github.com/users/mytika/repos", "events_url": "https://api.github.com/users/mytika/events{/privacy}", "received_events_url": "https://api.github.com/users/mytika/received_events", "type": "User", "site_admin": false}, "position": null, "line": null, "path": null, "commit_id": "affd14716732358086ef4ec4374246343294e110", "created_at": "2014-08-16T23:53:55Z", "updated_at": "2014-08-16T23:54:45Z", "author_association": "NONE", "body": "Hello Walter\nCould you tell me why here does not work? i'm error :\nthierry@toto:~/prestashopconnect_deps$ git clone git@github.com:OCA/connector.git\nCloning into 'connector'...\nPermission denied (publickey).\nfatal: The remote end hung up unexpectedly\nthierry@toto:~/prestashopconnect_deps$ \n\nCould you tell me what to do to make it work.\nThank you in advance\nbest regards\nThierry\n", "reactions": {"url": "https://api.github.com/repos/waltervargas/prestashoperpconnect/comments/7414948/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}}], "review_comments": []}}}